# -*- coding: utf-8 -*-
"""FuzzyReasoning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_7Zrnl3hgU0fGwSEYXOrnLGCDEiSsoBh
"""

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import matplotlib.pyplot as plt

# Restaurant Tipping System
def restaurant_tipping():
    # Define input and output variables
    service = ctrl.Antecedent(np.arange(0, 11, 1), 'service')
    food = ctrl.Antecedent(np.arange(0, 11, 1), 'food')
    tip = ctrl.Consequent(np.arange(0, 26, 1), 'tip')

    # Define membership functions
    service.automf(3)
    food.automf(3)
    tip['low'] = fuzz.trimf(tip.universe, [0, 0, 13])
    tip['medium'] = fuzz.trimf(tip.universe, [0, 13, 25])
    tip['high'] = fuzz.trimf(tip.universe, [13, 25, 25])

    # Define fuzzy rules
    rule1 = ctrl.Rule(service['poor'] | food['poor'], tip['low'])
    rule2 = ctrl.Rule(service['average'], tip['medium'])
    rule3 = ctrl.Rule(service['good'] | food['good'], tip['high'])

    # Create control system
    tipping_ctrl = ctrl.ControlSystem([rule1, rule2, rule3])
    tipping = ctrl.ControlSystemSimulation(tipping_ctrl)

    # Input values (changed for different results)
    tipping.input['service'] = 2.0
    tipping.input['food'] = 5.0

    # Compute the result
    tipping.compute()

    # Print and visualize the result
    print(f"Tip: {tipping.output['tip']:.2f}")
    tip.view(sim=tipping)

# ABS Brake System
def abs_brake_system():
    # Define input and output variables
    speed = ctrl.Antecedent(np.arange(0, 101, 1), 'speed')
    slip = ctrl.Antecedent(np.arange(0, 11, 1), 'slip')
    brake = ctrl.Consequent(np.arange(0, 101, 1), 'brake')

    # Define membership functions
    speed.automf(3)
    slip.automf(3)
    brake['low'] = fuzz.trimf(brake.universe, [0, 0, 50])
    brake['medium'] = fuzz.trimf(brake.universe, [0, 50, 100])
    brake['high'] = fuzz.trimf(brake.universe, [50, 100, 100])

    # Define fuzzy rules
    rule1 = ctrl.Rule(speed['poor'] | slip['poor'], brake['high'])
    rule2 = ctrl.Rule(speed['average'], brake['medium'])
    rule3 = ctrl.Rule(speed['good'] | slip['good'], brake['low'])

    # Create control system
    braking_ctrl = ctrl.ControlSystem([rule1, rule2, rule3])
    braking = ctrl.ControlSystemSimulation(braking_ctrl)

    # Input values (changed for different results)
    braking.input['speed'] = 20
    braking.input['slip'] = 9

    # Compute the result
    braking.compute()

    # Print and visualize the result
    print(f"Brake: {braking.output['brake']:.2f}")
    brake.view(sim=braking)

"""# Result Reproduce FUZZY reasoning"""

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import matplotlib.pyplot as plt

# Restaurant Tipping System
def restaurant_tipping():
    # Define input and output variables
    service = ctrl.Antecedent(np.arange(0, 11, 1), 'service')
    food = ctrl.Antecedent(np.arange(0, 11, 1), 'food')
    tip = ctrl.Consequent(np.arange(0, 26, 1), 'tip')

    # Define membership functions
    service.automf(3)
    food.automf(3)
    tip['low'] = fuzz.trimf(tip.universe, [0, 0, 13])
    tip['medium'] = fuzz.trimf(tip.universe, [0, 13, 25])
    tip['high'] = fuzz.trimf(tip.universe, [13, 25, 25])

    # Define fuzzy rules
    rule1 = ctrl.Rule(service['poor'] | food['poor'], tip['low'])
    rule2 = ctrl.Rule(service['average'], tip['medium'])
    rule3 = ctrl.Rule(service['good'] | food['good'], tip['high'])

    # Create control system
    tipping_ctrl = ctrl.ControlSystem([rule1, rule2, rule3])
    tipping = ctrl.ControlSystemSimulation(tipping_ctrl)

    # Input values
    tipping.input['service'] = 6.5
    tipping.input['food'] = 9.8

    # Compute the result
    tipping.compute()

    # Print and visualize the result
    print(f"Tip: {tipping.output['tip']:.2f}")
    tip.view(sim=tipping)

# ABS Brake System
def abs_brake_system():
    # Define input and output variables
    speed = ctrl.Antecedent(np.arange(0, 101, 1), 'speed')
    slip = ctrl.Antecedent(np.arange(0, 11, 1), 'slip')
    brake = ctrl.Consequent(np.arange(0, 101, 1), 'brake')

    # Define membership functions
    speed.automf(3)
    slip.automf(3)
    brake['low'] = fuzz.trimf(brake.universe, [0, 0, 50])
    brake['medium'] = fuzz.trimf(brake.universe, [0, 50, 100])
    brake['high'] = fuzz.trimf(brake.universe, [50, 100, 100])

    # Define fuzzy rules
    rule1 = ctrl.Rule(speed['poor'] | slip['poor'], brake['high'])
    rule2 = ctrl.Rule(speed['average'], brake['medium'])
    rule3 = ctrl.Rule(speed['good'] | slip['good'], brake['low'])

    # Create control system
    braking_ctrl = ctrl.ControlSystem([rule1, rule2, rule3])
    braking = ctrl.ControlSystemSimulation(braking_ctrl)

    # Input values
    braking.input['speed'] = 70
    braking.input['slip'] = 3

    # Compute the result
    braking.compute()

    # Print and visualize the result
    print(f"Brake: {braking.output['brake']:.2f}")
    brake.view(sim=braking)

# Run the systems
restaurant_tipping()
abs_brake_system()
plt.show()

"""# Plane Ticket Booking"""

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import matplotlib.pyplot as plt

# Plane Ticket Pricing System
def plane_ticket_pricing():
    # Define input and output variables
    demand = ctrl.Antecedent(np.arange(0, 11, 1), 'demand')
    season = ctrl.Antecedent(np.arange(0, 11, 1), 'season')
    price = ctrl.Consequent(np.arange(100, 1001, 1), 'price')

    # Define membership functions
    demand.automf(3)    # poor, average, good
    season.automf(3)    # poor, average, good

    price['low'] = fuzz.trimf(price.universe, [100, 100, 500])
    price['medium'] = fuzz.trimf(price.universe, [100, 500, 1000])
    price['high'] = fuzz.trimf(price.universe, [500, 1000, 1000])

    # Define fuzzy rules
    rule1 = ctrl.Rule(demand['poor'] | season['poor'], price['low'])
    rule2 = ctrl.Rule(demand['average'] | season['average'], price['medium'])
    rule3 = ctrl.Rule(demand['good'] | season['good'], price['high'])

    # Create control system
    price_ctrl = ctrl.ControlSystem([rule1, rule2, rule3])
    pricing = ctrl.ControlSystemSimulation(price_ctrl)

    # Input values
    pricing.input['demand'] = 7.2   # example: demand relatively high
    pricing.input['season'] = 8.5   # example: peak season

    # Compute the result
    pricing.compute()

    # Print and visualize the result
    print(f"Ticket Price: ${pricing.output['price']:.2f}")
    price.view(sim=pricing)

# Run the system
plane_ticket_pricing()
plt.show()

"""# Traffic Light Control System"""

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import matplotlib.pyplot as plt

# Traffic Light System with unique membership shapes
def traffic_light_control_unique():
    # Define input and output variables
    traffic = ctrl.Antecedent(np.arange(0, 11, 1), 'traffic')
    pedestrian = ctrl.Antecedent(np.arange(0, 11, 1), 'pedestrian')
    green = ctrl.Consequent(np.arange(0, 81, 1), 'green')

    # -------------------------
    # Custom UNIQUE membership functions
    # -------------------------

    # Traffic density (Gaussian)
    traffic['low'] = fuzz.gaussmf(traffic.universe, 2, 1.5)
    traffic['medium'] = fuzz.gaussmf(traffic.universe, 5, 1.5)
    traffic['high'] = fuzz.gaussmf(traffic.universe, 8, 1.5)

    # Pedestrian load (Bell-shaped)
    pedestrian['low'] = fuzz.gbellmf(pedestrian.universe, 2, 4, 2)
    pedestrian['medium'] = fuzz.gbellmf(pedestrian.universe, 2, 4, 5)
    pedestrian['high'] = fuzz.gbellmf(pedestrian.universe, 2, 4, 8)

    # Green light duration (Trapezoidal)
    green['short'] = fuzz.trapmf(green.universe, [0, 0, 10, 30])
    green['medium'] = fuzz.trapmf(green.universe, [20, 30, 50, 60])
    green['long'] = fuzz.trapmf(green.universe, [50, 65, 80, 80])

    # -------------------------
    # Rules
    # -------------------------
    rule1 = ctrl.Rule(traffic['low'] & pedestrian['low'], green['short'])
    rule2 = ctrl.Rule(traffic['medium'] | pedestrian['medium'], green['medium'])
    rule3 = ctrl.Rule(traffic['high'] | pedestrian['high'], green['long'])

    # Control System
    green_ctrl = ctrl.ControlSystem([rule1, rule2, rule3])
    controller = ctrl.ControlSystemSimulation(green_ctrl)

    # Example input values (adjust any way you like)
    controller.input['traffic'] = 7     # high traffic
    controller.input['pedestrian'] = 4  # medium pedestrians

    # Compute
    controller.compute()

    print(f"Green Light Duration: {controller.output['green']:.2f} seconds")

    # Unique output graph
    green.view(sim=controller)

# Run system
traffic_light_control_unique()
plt.show()