# -*- coding: utf-8 -*-
"""LAB2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f-1_2v19aytMikqUannm8Iw5OAUw77jk
"""



"""# **List**

# **Task 1: List**
"""

# Create the list of 10 integers
numbers=[1, 10, 15, 12, 25, 35, 45, 55, 60, 65]
print(numbers)

# Find and print the sum, maximum, minimum

print('Sum:',sum(numbers))
print('Max:', max(numbers))
print('min:',min(numbers))

# Add and remove the element

numbers.append(70)
numbers.remove(25)
print('Updated list:',numbers)

# Sort ascending and descending
numbers.sort()
print('Ascending:', numbers)
numbers.reverse()
print('Descending:', numbers)

"""# **Task 2: Tuples**"""

# Create a tuple
fruits = ('apple','banana','watermelon','mango','grapes')
print('Second element:', fruits[1])
print('last element:', fruits[-1])

# Cannot perform updations

fruits_list=list(fruits)
fruits_list.append('guava')
print(fruits_list)

"""# **Task 3: Sets**"""

A={1,2,3,4,5,}
B={2,4,6,8,10,}
print('Union:', A | B)
print('Intersection:', A & B)
print('Difference:', A - B)

"""# **Task 4: Dictionary**"""

# Create of distionary of friends and there marks
friends={'shoaib': 98,'ismail': 99,'usman':80,'mohiz':85}

# Print keys and values
print('key:',friends.keys())
print('values:',friends.values())

# Update values
friends['ismail']=100
print(friends)

"""# **Task 5: Numpy**"""



"""# **Task 6: Matplolibs**"""

